apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.firebase.crashlytics'

buildscript {
    repositories {
        google()
    }

    dependencies {
    }
}

repositories {
    google()
}



android {
    compileSdk 35
    signingConfigs {
        release {
            storeFile file(RELEASE_STORE_FILE)
            storePassword "$kspass"
            keyAlias RELEASE_KEY_ALIAS
            keyPassword "$kspass"
        }
    }
    defaultConfig {
        applicationId "com.sahnisemanyazilim.ezanisaat"
        minSdkVersion 21
        targetSdk 35
        versionCode 10
        versionName "1.3b1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    productFlavors {
    }
    namespace 'com.sahnisemanyazilim.ezanisaat'
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    api 'androidx.appcompat:appcompat:1.7.0'
    api 'androidx.constraintlayout:constraintlayout:2.2.1'
    api 'com.google.android.material:material:1.13.0-alpha11'
    //api 'com.google.firebase:firebase-core:21.1.1'
    api 'com.squareup.retrofit2:retrofit:2.11.0'
    api 'com.google.code.gson:gson:2.11.0'
    api 'com.squareup.retrofit2:converter-gson:2.11.0'
    api 'com.google.guava:guava:33.4.0-android'
    implementation(platform('com.google.firebase:firebase-bom:33.10.0'))

    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-analytics")

    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation "androidx.viewpager2:viewpager2:1.1.0"

    // (Java only)
    implementation "androidx.work:work-runtime:2.10.0"
    implementation "androidx.concurrent:concurrent-futures:1.2.0"
}


apply plugin: 'com.google.gms.google-services'